name: Python CI

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      
      - name: Run Pyright
        run: |
          cat pyrightconfig.json
          pyright

      - name: Run Tests
        run: pytest tests/
