name: Python CI

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/slipstreamm/disagreement-image:latest
      network: host
      options: --user 1001:1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Pyright
        run: pyright

      - name: Run Tests
        run: pytest tests/
